# Common configurations

imageCredentials:
  password: ""

stage: ""
domain: ""
license: ""
superusers: ""
mongoUrl: ""
redisUrl: ""

# Kubernetes Ingress configuration

ingress:
  class: ""


# API configurations
api:
  imageTag: "1.7.35"
  replicas: 1
  cpu: ""
  memory: ""
  debug: ""

  service:
    type: ""


# Frontend configurations
frontend:
  imageTag: "2.4.9"
  replicas: 1
  cpu: ""
  memory: ""

  service:
    type: ""


# Proxy configurations
proxy:
  imageTag: "1.0.22"
  replicas: 1
  cpu: ""
  memory: ""
  debug: ""

  service: 
    type: ""


# Recording configurations
recording:
  imageTag: "1.0.7"
  replicas: 1
  cpu: ""
  memory: ""
  debug: ""

  service:
    type: ""


# Sockets configurations
sockets:
  imageTag: "1.2.1"
  replicas: 1
  cpu: ""
  memory: ""
  debug: ""

  service:
    type: ""