# Common configurations

imageCredentials:
  password: ""

domain: ""
license: ""
superusers: ""
mongo:
  url: ""
redis:
  url: ""
stage: "enterprise"
ssl:
  generator: ""

# Kubernetes Ingress configuration
ingress:
  class: ""
  annotations: {}

# Persistent Volume Storage
storage:
  size: "50Gi"
  type: "" # See available types below and required configurations
  hostname: ""
  filesharename: ""
  
  # When NFS Server Provisioner is deployed inside the Kubernetes cluster
  # type: internal
  
  # When using external NFS outside cluster such as Azure Fileshare, GCP Filestore, On-prem NFS Server
  # type: external
  # hostname: ""
  # filesharename: ""

# API configurations
api:
  replicas: 1
  cpu: ""
  memory: ""
  debug: ""

  service:
    type: ""


# Frontend configurations
frontend:
  replicas: 1
  cpu: ""
  memory: ""

  service:
    type: ""


# Proxy configurations
proxy:
  replicas: 1
  cpu: ""
  memory: ""
  debug: ""

  service:
    type: ""


# Recording configurations
recording:
  replicas: 1
  cpu: ""
  memory: ""
  debug: ""

  service:
    type: ""


# Sockets configurations
sockets:
  replicas: 1
  cpu: ""
  memory: ""
  debug: ""

  service:
    type: ""
