# Common configurations

imageCredentials:
  password: ""

domain: ""
license: ""
superusers: ""
mongo:
  url: ""
redis:
  url: ""
stage: "enterprise"
ssl:
  generator: ""

# Kubernetes Ingress configuration
ingress:
  class: ""
  annotations: {}

# Persistent Volume Storage
storage:
  size: "50Gi"
  type: "" # See available types below and required configs
  
  ## NFS Provisioner
  #type: "nfs_provisioner"
  
  ## GCP Filestore
  #type: "filestore"
  #filestore:
  #  ipAddress: ""
  #  fsName: ""

# API configurations
api:
  replicas: 1
  cpu: ""
  memory: ""
  debug: ""

  service:
    type: ""


# Frontend configurations
frontend:
  replicas: 1
  cpu: ""
  memory: ""

  service:
    type: ""


# Proxy configurations
proxy:
  replicas: 1
  cpu: ""
  memory: ""
  debug: ""

  service:
    type: ""


# Recording configurations
recording:
  replicas: 1
  cpu: ""
  memory: ""
  debug: ""

  service:
    type: ""


# Sockets configurations
sockets:
  replicas: 1
  cpu: ""
  memory: ""
  debug: ""

  service:
    type: ""
