# Common configurations

imageCredentials:
  registry: ghcr.io
  username: cobrowse-enterprise
  password: ""

stage: ""
domain: ""
license: ""
superusers: ""
mongoUrl: ""
redisUrl: ""

# Kubernetes Ingress configuration

ingress:
  class: ""


# API configurations
api:
  image: ""
  replicas: 1
  cpu: ""
  memory: ""
  debug: ""

  service:
    type: ""


# Frontend configurations
frontend:
  image: ""
  replicas: 1
  cpu: ""
  memory: ""
  debug: ""

  service:
    type: ""


# Proxy configurations
proxy:
  image: ""
  replicas: 1
  cpu: ""
  memory: ""
  debug: ""

  service: 
    type: ""


# Recording configurations
recording:
  image: ""
  replicas: 1
  cpu: ""
  memory: ""
  debug: ""

  service:
    type: ""


# Sockets configurations
sockets:
  image: ""
  replicas: 1
  cpu: ""
  memory: ""
  debug: ""

  service:
    type: ""