# Common configurations

imageCredentials:
  registry: ghcr.io
  username: ""
  password: ""
  email: ""

stage: ""
region: ""
domain: ""
licenseKey: ""
accountCreators: ""
superusers: ""

mongoUrl: ""
smtpUrl: ""
redisUrl: ""

ingress:
  class: ""

# API configurations
api:
  port: "8080" 
  image: ""
  replicas: 1
  cpu: "256m"
  memory: "256Mi"
  debug: ""

  service:
    type: "ClusterIP"


# Frontend configurations
frontend:
  port: "8080"
  image: ""
  replicas: 1
  cpu: "256m"
  memory: "256Mi"
  debug: ""

  service:
    type: "ClusterIP"


# Proxy configurations
proxy:
  port: "8080"
  image: ""
  replicas: 1
  cpu: "256m"
  memory: "256Mi"
  debug: ""

  service: 
    type: "ClusterIP"


# Recording configurations
recording:
  port: "8080"
  image: ""
  replicas: 1
  cpu: "256m"
  memory: "256Mi"
  debug: ""

  service:
    type: "ClusterIP"


# Sockets configurations
sockets:
  port: "8080"
  image: ""
  replicas: 1
  cpu: "256m"
  memory: "256Mi"
  debug: ""

  service:
    type: "ClusterIP"
  
  storage: 
    size: "50Gi" # should be lower than NFS provisioner storage size
    className: "nfs" 
  mountPath: "/data/traces"