apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-api-envvars
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    stage: {{ .Values.stage | quote }}
type: Opaque
data:
  PORT: {{ default "8080" .Values.api.port | b64enc | quote }}
  STAGE: {{ .Values.stage | b64enc | quote }}
  DEBUG: {{ default "" .Values.proxy.debug | b64enc | quote }}
  mongo_url: {{ default "" .Values.mongoUrl | b64enc | quote }}
  redis_url: {{ default "" .Values.redisUrl | b64enc | quote }}
  frontend_url: {{ printf "https://%s" .Values.domain | b64enc | quote }}
  smtp_url: {{ default "" .Values.smtpUrl | b64enc | quote }}
  control__url_template: {{ printf "https://%s" .Values.domain | b64enc | quote }}
  streaming__url_template: {{ printf "https://%s" .Values.domain | b64enc | quote }}
  streaming__default_region: {{ default "api" | b64enc | quote }}
  streaming__locate_url: {{ printf "https://%s/sockets/1/%s" .Values.domain .Values.region | b64enc | quote }}
  license_key: {{ default "" .Values.licenseKey | b64enc | quote }}
  account_creators: {{ default "" .Values.accountCreators | b64enc | quote }}
  superusers: {{ default "" .Values.superusers | b64enc | quote }}