apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    component: api
    app: {{ template "fullname" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    stage: {{ .Values.stage | quote }}
spec:
  replicas: {{ .Values.api.replicas | default "1" }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  minReadySeconds: 30
  selector:
    matchLabels:
      component: api
      stage: {{ .Values.stage | quote }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/api-secret.yaml") . | sha256sum }}
      labels:
        component: api
        stage: {{ .Values.stage | quote }}
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: {{ .Release.Name }}-api-envvars
        image: ghcr.io/cobrowseio/cobrowse-api-enterprise:1.12.1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /up
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: api
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /up
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: {{ .Values.api.cpu | default "256m" }}
            memory: {{ .Values.api.memory | default "256Mi" }}
          requests:
            cpu: {{ .Values.api.cpu | default "256m" }}
            memory: {{ .Values.api.memory | default "256Mi" }}
      imagePullSecrets:
      - name: {{ .Release.Name }}-docker-cfg
