apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-svc
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    stage: {{ .Values.stage | quote }}
  annotations:
  {{- if eq .Values.ingress.class "gce" }}
    cloud.google.com/neg: '{"ingress": true}'
  {{- end }}
spec:
  ports:
  - port: {{ int .Values.frontend.port }}
    protocol: TCP
    targetPort: {{ int .Values.frontend.port }}
  selector:
    component: frontend
    stage: {{ .Values.stage | quote }}
  type: {{ .Values.frontend.service.type | default "ClusterIP" }}