apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-frontend-envvars
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    stage: {{ .Values.stage | quote }}
type: Opaque
data:
  COBROWSE_ENTERPRISE: {{ default "true" | b64enc | quote }}