apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-proxy
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    component: proxy
    app: {{ template "fullname" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    stage: {{ .Values.stage | quote }}
spec:
  replicas: {{ .Values.proxy.replicas | default "1" }}
  selector:
    matchLabels:
      component: proxy
      stage: {{ .Values.stage | quote }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/proxy-secret.yaml") . | sha256sum }}
      labels:
        component: proxy
        stage: {{ .Values.stage | quote }}
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: {{ .Release.Name }}-proxy-envvars
        image: {{ .Values.proxy.image }} 
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /up
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: proxy
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /up
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: {{ .Values.proxy.cpu | default "256m"}}
            memory: {{ .Values.proxy.memory | default "256Mi"}}
          requests:
            cpu: {{ .Values.proxy.cpu | default "256m"}}
            memory: {{ .Values.proxy.memory | default "256Mi"}}
      imagePullSecrets:
      - name: {{ .Release.Name }}-docker-cfg