apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-recording
  namespace: {{ .Release.Namespace | default "default" }}
  annotations:
  labels:
    component: recording
    app: {{ template "fullname" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    stage: {{ .Values.stage | quote }}
spec:
  replicas: {{ .Values.recording.replicas | default "1" }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  minReadySeconds: 30
  selector:
    matchLabels:
      component: recording
      stage: {{ .Values.stage | quote }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/recording-secret.yaml") . | sha256sum }}
      labels:
        component: recording
        stage: {{ .Values.stage | quote }}
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: {{ .Release.Name }}-recording-envvars
        image: ghcr.io/cobrowseio/cobrowse-recording-enterprise:1.0.11
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /up
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: recording
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /up
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: {{ .Values.recording.cpu | default "256m"}}
            memory: {{ .Values.recording.memory | default "256Mi"}}
          requests:
            cpu: {{ .Values.recording.cpu | default "256m"}}
            memory: {{ .Values.recording.memory | default "256Mi"}}
      imagePullSecrets:
      - name: {{ .Release.Name }}-docker-cfg
