apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-recording-envvars
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    stage: {{ .Values.stage | quote }}
type: Opaque
data:
  PORT: {{ default "8080" .Values.recording.port | b64enc | quote }}
  STAGE: {{ default "" .Values.stage | b64enc | quote }}
  DEBUG: {{ default "" .Values.recording.debug | b64enc | quote }}