apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sockets-envvars
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    stage: {{ .Values.stage | quote }}
type: Opaque
data:
  PORT: {{ "8080" | b64enc | quote }}
  STAGE: {{ default "" .Values.stage | b64enc | quote }}
  DEBUG: {{ default "" .Values.sockets.debug | b64enc | quote }}
  api_url: {{ printf "http://%s-api-svc:8080" .Release.Name | b64enc | quote }}
  peering_port: {{ "8081" | b64enc | quote }}
  peering_token: {{ randAlphaNum 32 | b64enc | quote }}
  peering_hostname_template: {{ printf "<%%=hostname%%>.%s-sockets-headless" .Release.Name | b64enc | quote }}
  redis_url: {{ default "" .Values.redis.url | b64enc | quote }}
