apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sockets-svc
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    stage: {{ .Values.stage | quote }}
  annotations:
  {{- if eq .Values.ingress.class "gce" }}
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"ports": {"8080":"api-sockets-backendconfig"}}'
  {{- end }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    component: sockets
    stage: {{ .Values.stage | quote }}
  type: {{ .Values.sockets.service.type | default "ClusterIP" }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sockets-headless
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    stage: {{ .Values.stage | quote }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    component: sockets
    stage: {{ .Values.stage | quote }}
  type: "ClusterIP"
  clusterIP: None
